apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.0.0
        profileName: 'default-profile : open /Users/martinmulholland/helm/chart-verifier/pkg/chartverifier/profiles/profile-1.0.0.yaml:
            no such file or directory'
        chart-uri: src
        digest: sha256:f114b1dc9ba92213525c0d848e2f735795e23c6a18cb1132e476d3a48826f7f1
        lastCertifiedTimestamp: "2021-06-22T17:28:30.450582-04:00"
        certifiedOpenShiftVersions: 4.7.8
    chart:
        name: psql-service
        home: ""
        sources: []
        version: 0.1.8
        description: A Helm chart for a RedHat Certified PSQL
        keywords: []
        maintainers: []
        icon: ""
        apiversion: v2
        condition: ""
        tags: ""
        appversion: 10.0.0
        deprecated: false
        annotations:
            charts.openshift.io/archs: x86_64
            charts.openshift.io/name: PSQL RedHat Demo Chart
            charts.openshift.io/provider: RedHat
            charts.openshift.io/supportURL: https://github.com/dperaza4dustbit/helm-chart
        kubeversion: 1.20.0
        dependencies: []
        type: application
    chart-overrides: ""
results:
  - check: has-kubeversion
    type: Mandatory
    outcome: PASS
    reason: Kubernetes version specified
  - check: not-contains-crds
    type: Mandatory
    outcome: PASS
    reason: Chart does not contain CRDs
  - check: helm-lint
    type: Mandatory
    outcome: PASS
    reason: Helm lint successful
  - check: not-contain-csi-objects
    type: Mandatory
    outcome: PASS
    reason: CSI objects do not exist
  - check: images-are-certified
    type: Mandatory
    outcome: PASS
    reason: 'Image is Red Hat certified : registry.access.redhat.com/rhscl/postgresql-10-rhel7:latest'
  - check: contains-values
    type: Mandatory
    outcome: PASS
    reason: Values file exist
  - check: is-helm-v3
    type: Mandatory
    outcome: PASS
    reason: API version is V2, used in Helm 3
  - check: contains-test
    type: Mandatory
    outcome: PASS
    reason: Chart test files exist
  - check: contains-values-schema
    type: Mandatory
    outcome: PASS
    reason: Values schema file exist
  - check: chart-testing
    type: Mandatory
    outcome: PASS
    reason: passy
  - check: has-readme
    type: Mandatory
    outcome: PASS
    reason: Chart has a README

