2021/07/09 13:05:40 [INFO] Missing required value: .Values.global.persistence.claims.name cannot be empty.
apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.1.0
        profile:
            VendorType: partner
            version: v1.0
        chart-uri: https://github.com/IBM/charts/blob/master/repo/ibm-helm/ibm-object-storage-plugin-2.1.2.tgz?raw=true
        digest: sha256:e7cacf93d397b58c64f9c113cc0671e6e920022bf4227cab291e18c6e3827954
        digests:
            chart: sha256:e7cacf93d397b58c64f9c113cc0671e6e920022bf4227cab291e18c6e3827954
            package: 467896f2c66484751704397c19e29cfdbcada30a8f9ab3c0168ad3db34821099
        lastCertifiedTimestamp: "2021-07-09T13:05:40.77301-04:00"
        certifiedOpenShiftVersions: N/A
    chart: |
        apiVersion: v2
        appVersion: 10.0.0
        dependencies:
        - alias: sch
          name: ibm-sch
          repository: '@sch'
          version: 1.2.15
        description: |-
          IBM Order management Software Professional Edition v10 provides cross-channel order orchestration capabilities to enable intelligent brokering of orders across many disparate systems. It also provides a global view of inventory across the supply chain and enables business users to make changes to order process.
          Documentation
          For additional details regarding install parameters check http://ibm.biz/oms-helm-readme.
          License
          By installing this product you accept the license terms http://ibm.biz/oms-license and http://ibm.biz/oms-apps-license.
        home: http://ibm.biz/oms-home
        icon: https://raw.githubusercontent.com/IBM/charts/master/logo/ibm-oms-logo.png
        keywords:
        - oms
        - sterling
        - yantra
        - order
        - fulfillment
        - om
        - amd64
        - ppc64le
        - framework
        - Commercial
        - RHOCP
        - IKS
        - Other
        kubeVersion: '>=1.16.0-0'
        maintainers:
        - name: IBM
        name: ibm-oms-pro-prod
        type: application
        version: 6.0.1
    chart-overrides: ""
results:
  - check: v1.0/chart-testing
    type: Mandatory
    outcome: FAIL
    reason: Chart testing passed
  - check: v1.0/has-readme
    type: Mandatory
    outcome: PASS
    reason: Chart has a README
  - check: v1.0/is-helm-v3
    type: Mandatory
    outcome: PASS
    reason: API version is V2, used in Helm 3
  - check: v1.0/contains-values-schema
    type: Mandatory
    outcome: PASS
    reason: Values schema file exist
  - check: v1.0/has-kubeversion
    type: Mandatory
    outcome: PASS
    reason: Kubernetes version specified
  - check: v1.0/images-are-certified
    type: Mandatory
    outcome: PASS
    reason: |-
        Image is Red Hat certified : ibmcom/ibmcloud-object-storage-driver@sha256:324787a10da384bb7bb441538eb65846c9df57bfd0e8a37a2f3efaeb423c2bc9
        Image is Red Hat certified : ibmcom/ibmcloud-object-storage-plugin@sha256:4adddd3d619c056ed6fd3dc00864e4b7af140dd731557c2e64bfd6ced4232bbf
  - check: v1.0/contains-test
    type: Mandatory
    outcome: PASS
    reason: Chart test files exist
  - check: v1.0/contains-values
    type: Mandatory
    outcome: PASS
    reason: Values file exist
  - check: v1.0/not-contains-crds
    type: Mandatory
    outcome: PASS
    reason: Chart does not contain CRDs
  - check: v1.0/helm-lint
    type: Mandatory
    outcome: PASS
    reason: Helm lint successful
  - check: v1.0/not-contain-csi-objects
    type: Mandatory
    outcome: PASS
    reason: CSI objects do not exist

