apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.5.0
        profile:
            VendorType: partner
            version: v1.1
        chart-uri: ../charts/charts/redhat/redhat/data-grid/8.3.0/data-grid-8.3.0.tgz
        digests:
            chart: sha256:4a60f63bec9744cc6b6261ae1b81670a96c3e9d95c1bb259894b4b2220a42549
            package: 4415500e239a902c57ebe2f856ae26dd50829511748d1cde5ff08e803d4a540a
        lastCertifiedTimestamp: "2022-02-24T15:20:18.746884-05:00"
        testedOpenShiftVersion: N/A
        supportedOpenShiftVersions: N/A
        providerControlledDelivery: false
    chart:
        name: data-grid
        home: https://access.redhat.com/documentation/en-us/red_hat_data_grid/8.3
        sources:
            - https://github.com/infinispan/infinispan
            - https://github.com/infinispan/infinispan-helm-charts
        version: 8.3.0
        description: A Helm chart that lets you build and deploy Red Hat Data Grid clusters.
        keywords: []
        maintainers:
            - name: Red Hat
              email: ""
              url: https://access.redhat.com/documentation/en-us/red_hat_data_grid/8.3
        icon: https://access.redhat.com/webassets/avalon/d/red-hat-data-grid/images/rhdg-icon.png
        apiversion: v2
        condition: ""
        tags: ""
        appversion: "8.3"
        deprecated: false
        annotations: {}
        kubeversion: ""
        dependencies: []
        type: application
    chart-overrides: ""
results:
    - check: v1.0/not-contain-csi-objects
      type: Mandatory
      outcome: PASS
      reason: CSI objects do not exist
    - check: v1.0/images-are-certified
      type: Mandatory
      outcome: FAIL
      reason: |-
        Image is not Red Hat certified : registry.redhat.io/datagrid/datagrid-8-rhel8:1.3 : No images found for Registry/Repository: registry.redhat.io/datagrid/datagrid-8-rhel8
        Image is not Red Hat certified : quay.io/repository/quay/busybox : No images found for Registry/Repository: quay.io/repository/quay/busybox
    - check: v1.0/has-readme
      type: Mandatory
      outcome: PASS
      reason: Chart has a README
    - check: v1.0/is-helm-v3
      type: Mandatory
      outcome: PASS
      reason: API version is V2, used in Helm 3
    - check: v1.0/contains-test
      type: Mandatory
      outcome: PASS
      reason: Chart test files exist
    - check: v1.0/contains-values
      type: Mandatory
      outcome: PASS
      reason: Values file exist
    - check: v1.0/contains-values-schema
      type: Mandatory
      outcome: PASS
      reason: Values schema file exist
    - check: v1.0/not-contains-crds
      type: Mandatory
      outcome: PASS
      reason: Chart does not contain CRDs
    - check: v1.0/required-annotations-present
      type: Mandatory
      outcome: FAIL
      reason: 'Missing required annotations: [charts.openshift.io/name]'
    - check: v1.1/has-kubeversion
      type: Mandatory
      outcome: FAIL
      reason: Kubernetes version is not specified
    - check: v1.0/helm-lint
      type: Mandatory
      outcome: PASS
      reason: Helm lint successful
    - check: v1.0/chart-testing
      type: Mandatory
      outcome: FAIL
      reason: timed out waiting for the condition

